import Head from 'next/head'
import Banner from '../components/Banner'
import Footer from '../components/Footer'
import Header from '../components/Header'
import HouseList from '../components/HouseList'


export default function Home() {


  return (
    <div>
      <Head>
        <title>Dream Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='max-w-[1440px] mx-auto bg-white'>
        <Header />
        <div className='min-h-[1800px]'>
          <Banner />
          <HouseList />
        </div>
        <Footer />
      </div>
    </div>
  )
}
